package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

public class FrmMenu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;

    public FrmMenu() {
        setUndecorated(true);
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("SIVIN");

        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, alto);
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_nuevoUsuario = new javax.swing.JMenuItem();
        jMenuItem_gestionarUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_nuevoProducto = new javax.swing.JMenuItem();
        jMenuItem_gestionarProducto = new javax.swing.JMenuItem();
        jMenuItem_actualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_nuevoCliente = new javax.swing.JMenuItem();
        jMenuItem_gestionarClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_nuevaCategoria = new javax.swing.JMenuItem();
        jMenuItem_gestionarCategorias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_nuevaVenta = new javax.swing.JMenuItem();
        jMenuItem_gestionarVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_reportesClientes = new javax.swing.JMenuItem();
        jMenuItem_reportesCategoria = new javax.swing.JMenuItem();
        jMenuItem_reportesProducto = new javax.swing.JMenuItem();
        jMenuItem_reportesVentas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_verHistorial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/freelancer_1.png"))); // NOI18N
        jMenu1.setText("USUARIO");
        jMenu1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_nuevoUsuario.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-user.png"))); // NOI18N
        jMenuItem_nuevoUsuario.setText("Nuevo Usuario");
        jMenuItem_nuevoUsuario.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu1.add(jMenuItem_nuevoUsuario);

        jMenuItem_gestionarUsuarios.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cogwheel.png"))); // NOI18N
        jMenuItem_gestionarUsuarios.setText("Gestionar Usuarios");
        jMenuItem_gestionarUsuarios.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu1.add(jMenuItem_gestionarUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parcel.png"))); // NOI18N
        jMenu2.setText("PRODUCTO");
        jMenu2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_nuevoProducto.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-product.png"))); // NOI18N
        jMenuItem_nuevoProducto.setText("Nuevo Producto");
        jMenuItem_nuevoProducto.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevoProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_nuevoProducto);

        jMenuItem_gestionarProducto.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_gestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cogwheel.png"))); // NOI18N
        jMenuItem_gestionarProducto.setText("Gestionar Productos");
        jMenuItem_gestionarProducto.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_gestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_gestionarProducto);

        jMenuItem_actualizarStock.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_actualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-button.png"))); // NOI18N
        jMenuItem_actualizarStock.setText("Actualizar Stock");
        jMenuItem_actualizarStock.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_actualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_actualizarStockActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_actualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer-engagement.png"))); // NOI18N
        jMenu3.setText("CLIENTE");
        jMenu3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_nuevoCliente.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-user1.png"))); // NOI18N
        jMenuItem_nuevoCliente.setText("Nuevo Cliente");
        jMenuItem_nuevoCliente.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_nuevoCliente);

        jMenuItem_gestionarClientes.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_gestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crm_1.png"))); // NOI18N
        jMenuItem_gestionarClientes.setText("Gestionar Clientes");
        jMenuItem_gestionarClientes.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_gestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_gestionarClientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application.png"))); // NOI18N
        jMenu4.setText("CATEGORIA");
        jMenu4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_nuevaCategoria.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_nuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application.png"))); // NOI18N
        jMenuItem_nuevaCategoria.setText("Nueva Categoría");
        jMenuItem_nuevaCategoria.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_nuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_nuevaCategoria);

        jMenuItem_gestionarCategorias.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_gestionarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cogwheel.png"))); // NOI18N
        jMenuItem_gestionarCategorias.setText("Gestionar Categorías");
        jMenuItem_gestionarCategorias.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_gestionarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarCategoriasActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gestionarCategorias);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package-receipt.png"))); // NOI18N
        jMenu5.setText("FACTURAR");
        jMenu5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_nuevaVenta.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package-receipt.png"))); // NOI18N
        jMenuItem_nuevaVenta.setText("Nueva Venta");
        jMenuItem_nuevaVenta.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu5.add(jMenuItem_nuevaVenta);

        jMenuItem_gestionarVentas.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_gestionarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money-management.png"))); // NOI18N
        jMenuItem_gestionarVentas.setText("Gestionar Ventas");
        jMenuItem_gestionarVentas.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu5.add(jMenuItem_gestionarVentas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        jMenu6.setText("REPORTES");
        jMenu6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_reportesClientes.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_reportesClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analytics.png"))); // NOI18N
        jMenuItem_reportesClientes.setText("Reportes Clientes");
        jMenuItem_reportesClientes.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu6.add(jMenuItem_reportesClientes);

        jMenuItem_reportesCategoria.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_reportesCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChatGPT_Image_10_abr_2025__03_18_56_p.m.-removebg-preview (1).png"))); // NOI18N
        jMenuItem_reportesCategoria.setText("Reportes Categorías");
        jMenuItem_reportesCategoria.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_reportesCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reportesCategoriaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_reportesCategoria);

        jMenuItem_reportesProducto.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_reportesProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analysis.png"))); // NOI18N
        jMenuItem_reportesProducto.setText("Reportes Productos");
        jMenuItem_reportesProducto.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu6.add(jMenuItem_reportesProducto);

        jMenuItem_reportesVentas.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_reportesVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        jMenuItem_reportesVentas.setText("Reportes Ventas");
        jMenuItem_reportesVentas.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu6.add(jMenuItem_reportesVentas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/statistics.png"))); // NOI18N
        jMenu7.setText("HISTORIAL");
        jMenu7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_verHistorial.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_verHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/statistics.png"))); // NOI18N
        jMenuItem_verHistorial.setText("Ver Historial");
        jMenuItem_verHistorial.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenu7.add(jMenuItem_verHistorial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMenu8.setText("CERRAR SESION");
        jMenu8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(170, 50));

        jMenuItem_cerrarSesion.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jMenuItem_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMenuItem_cerrarSesion.setText("Cerrar Sesión");
        jMenuItem_cerrarSesion.setPreferredSize(new java.awt.Dimension(200, 35));
        jMenuItem_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cerrarSesionActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_cerrarSesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_gestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarProductoActionPerformed
        // TODO add your handling code here:
        InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
        jDesktopPane_menu.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);

    }//GEN-LAST:event_jMenuItem_gestionarProductoActionPerformed

    private void jMenuItem_actualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_actualizarStockActionPerformed
        // TODO add your handling code here:
        InterActualizarStock actualizarStock = new InterActualizarStock();
        jDesktopPane_menu.add(actualizarStock);
        actualizarStock.setVisible(true);
    }//GEN-LAST:event_jMenuItem_actualizarStockActionPerformed

    private void jMenuItem_nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevoClienteActionPerformed
        // TODO add your handling code here:
        InterCliente interCliente = new InterCliente();
        jDesktopPane_menu.add(interCliente);
        interCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevoClienteActionPerformed

    private void jMenuItem_reportesCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_reportesCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_reportesCategoriaActionPerformed

    private void jMenuItem_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cerrarSesionActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_cerrarSesionActionPerformed

    private void jMenuItem_nuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevaCategoriaActionPerformed
        // TODO add your handling code here:
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);

    }//GEN-LAST:event_jMenuItem_nuevaCategoriaActionPerformed

    private void jMenuItem_gestionarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarCategoriasActionPerformed
        // TODO add your handling code here:
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);

    }//GEN-LAST:event_jMenuItem_gestionarCategoriasActionPerformed

    private void jMenuItem_nuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevoProductoActionPerformed
        InterProducto InterProducto = new InterProducto();
        jDesktopPane_menu.add(InterProducto);
        InterProducto.setVisible(true);


    }//GEN-LAST:event_jMenuItem_nuevoProductoActionPerformed

    private void jMenuItem_gestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarClientesActionPerformed
        // TODO add your handling code here:
        InterGestionarCliente interGestionarCliente = new InterGestionarCliente();
        jDesktopPane_menu.add(interGestionarCliente);
        interGestionarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_actualizarStock;
    private javax.swing.JMenuItem jMenuItem_cerrarSesion;
    private javax.swing.JMenuItem jMenuItem_gestionarCategorias;
    private javax.swing.JMenuItem jMenuItem_gestionarClientes;
    private javax.swing.JMenuItem jMenuItem_gestionarProducto;
    private javax.swing.JMenuItem jMenuItem_gestionarUsuarios;
    private javax.swing.JMenuItem jMenuItem_gestionarVentas;
    private javax.swing.JMenuItem jMenuItem_nuevaCategoria;
    private javax.swing.JMenuItem jMenuItem_nuevaVenta;
    private javax.swing.JMenuItem jMenuItem_nuevoCliente;
    private javax.swing.JMenuItem jMenuItem_nuevoProducto;
    private javax.swing.JMenuItem jMenuItem_nuevoUsuario;
    private javax.swing.JMenuItem jMenuItem_reportesCategoria;
    private javax.swing.JMenuItem jMenuItem_reportesClientes;
    private javax.swing.JMenuItem jMenuItem_reportesProducto;
    private javax.swing.JMenuItem jMenuItem_reportesVentas;
    private javax.swing.JMenuItem jMenuItem_verHistorial;
    // End of variables declaration//GEN-END:variables
}
